Решение
dispersion01/hogwartsSwagger pull request #1
Opened 2022-04-30 10:09 UTC by dispersion01

2022-04-30 20:17 UTC, OKrylov requested changes
В целом направление решения верное, но есть несколько замечаний + не вижу аннотации по активации openapi

2022-04-30 20:17 UTC, OKrylov commented on src/main/java/ru/hogwarts/school/service/FacultyService.java
> +        return facultyMap.get(facultyMap.containsValue(color));
А как это работает?

2022-04-30 20:17 UTC, OKrylov commented on src/main/java/ru/hogwarts/school/service/StudentService.java
> +        return studentMap.get(age);
Возраст не есть id

2022-05-01 20:41 UTC, dispersion01 commented on src/main/java/ru/hogwarts/school/service/FacultyService.java
> +        return facultyMap.get(facultyMap.containsValue(color));
поправила, немного перепутала

2022-05-01 20:42 UTC, dispersion01 commented on src/main/java/ru/hogwarts/school/service/StudentService.java
> +        return studentMap.get(age);
тип поменяла на int

2022-05-01 20:43 UTC, dispersion01 commented on src/main/java/ru/hogwarts/school/service/StudentService.java
> +        return studentMap.get(age);
openapi у меня в depency  в файле pom.xml

2022-05-03 21:33 UTC, OKrylov approved these changes
По исправлениям все супер, замечаний нет

2022-05-03 21:33 UTC, OKrylov commented on src/main/java/ru/hogwarts/school/controller/FacultyController.java
> +    public Collection <Faculty> colorFaculty(@PathVariable String color) {
лишний пробел
```suggestion
    public Collection<Faculty> colorFaculty(@PathVariable String color) {
```

2022-05-07 19:49 UTC, dispersion01 commented
Merge будет произведен в рамках второго pullrequest

2022-05-07 19:49 UTC, closed without merging